<a href="https://colab.research.google.com/github/boemer00/deep_learning/blob/main/vectorize_neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

# Example values
D = 3
M = 2

W = np.array([[1, 2], [3, 4], [5, 6]])
x = np.array([[2], [3], [4]])
b = np.array([[1], [2]])

# Step 1: Transpose W
W_T = np.transpose(W)

# Step 2: Matrix multiplication
W_T_x = np.dot(W_T, x)

# Step 3: Adding bias
W_T_x_b = W_T_x + b

# Step 4: Applying the activation function (sigmoid)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

z = sigmoid(W_T_x_b)

print(W.shape)
print()
print(x.shape)
print()
print(b.shape)
print()

print("Step 1: Transpose W")
print(W_T)
print()

print("Step 2: Matrix multiplication")
print(W_T_x)
print()

print("Step 3: Adding bias")
print(W_T_x_b)
print()

print("Step 4: Applying the activation function (sigmoid)")
print(z)


(3, 2)

(3, 1)

(2, 1)

Step 1: Transpose W
[[1 3 5]
 [2 4 6]]

Step 2: Matrix multiplication
[[31]
 [40]]

Step 3: Adding bias
[[32]
 [42]]

Step 4: Applying the activation function (sigmoid)
[[1.]
 [1.]]
